/* tslint:disable */
/* eslint-disable */
/**
 * benzapp API
 * benzapp API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AdminUserDTO
 */
export interface AdminUserDTO {
    /**
     * 
     * @type {boolean}
     * @memberof AdminUserDTO
     */
    activated?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof AdminUserDTO
     */
    authorities?: any;
    /**
     * 
     * @type {string}
     * @memberof AdminUserDTO
     */
    createdBy?: any;
    /**
     * 
     * @type {Date}
     * @memberof AdminUserDTO
     */
    createdDate?: any;
    /**
     * 
     * @type {string}
     * @memberof AdminUserDTO
     */
    email?: any;
    /**
     * 
     * @type {string}
     * @memberof AdminUserDTO
     */
    firstName?: any;
    /**
     * 
     * @type {number}
     * @memberof AdminUserDTO
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof AdminUserDTO
     */
    imageUrl?: any;
    /**
     * 
     * @type {string}
     * @memberof AdminUserDTO
     */
    langKey?: any;
    /**
     * 
     * @type {string}
     * @memberof AdminUserDTO
     */
    lastModifiedBy?: any;
    /**
     * 
     * @type {Date}
     * @memberof AdminUserDTO
     */
    lastModifiedDate?: any;
    /**
     * 
     * @type {string}
     * @memberof AdminUserDTO
     */
    lastName?: any;
    /**
     * 
     * @type {string}
     * @memberof AdminUserDTO
     */
    login: any;
}
