/* tslint:disable */
/* eslint-disable */
/**
 * benzapp API
 * benzapp API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Delega
 */
export interface Delega {
    /**
     * 
     * @type {Cittadino}
     * @memberof Delega
     */
    cittadino?: any;
    /**
     * 
     * @type {number}
     * @memberof Delega
     */
    id?: any;
    /**
     * 
     * @type {Tessera}
     * @memberof Delega
     */
    tessera?: any;
}
