/* tslint:disable */
/* eslint-disable */
/**
 * benzapp API
 * benzapp API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Fascia
 */
export interface Fascia {
    /**
     * 
     * @type {Array&lt;Cittadino&gt;}
     * @memberof Fascia
     */
    cittadinos?: any;
    /**
     * 
     * @type {string}
     * @memberof Fascia
     */
    descrizione?: any;
    /**
     * 
     * @type {number}
     * @memberof Fascia
     */
    id?: any;
    /**
     * 
     * @type {number}
     * @memberof Fascia
     */
    scontoBenzina?: any;
    /**
     * 
     * @type {number}
     * @memberof Fascia
     */
    scontoGasolio?: any;
}
