/* tslint:disable */
/* eslint-disable */
/**
 * benzapp API
 * benzapp API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LoginVM
 */
export interface LoginVM {
    /**
     * 
     * @type {string}
     * @memberof LoginVM
     */
    password: any;
    /**
     * 
     * @type {boolean}
     * @memberof LoginVM
     */
    rememberMe?: any;
    /**
     * 
     * @type {string}
     * @memberof LoginVM
     */
    username: any;
}
