/* tslint:disable */
/* eslint-disable */
/**
 * benzapp API
 * benzapp API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Marchio
 */
export interface Marchio {
    /**
     * 
     * @type {Array&lt;Gestore&gt;}
     * @memberof Marchio
     */
    gestores?: any;
    /**
     * 
     * @type {number}
     * @memberof Marchio
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Marchio
     */
    immagine?: any;
    /**
     * 
     * @type {string}
     * @memberof Marchio
     */
    immagineContentType?: any;
    /**
     * 
     * @type {string}
     * @memberof Marchio
     */
    nome: any;
}
