/* tslint:disable */
/* eslint-disable */
/**
 * benzapp API
 * benzapp API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface NotificaDTO
 */
export interface NotificaDTO {
    /**
     * 
     * @type {Date}
     * @memberof NotificaDTO
     */
    data: any;
    /**
     * 
     * @type {number}
     * @memberof NotificaDTO
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof NotificaDTO
     */
    targa: any;
}
