/* tslint:disable */
/* eslint-disable */
/**
 * benzapp API
 * benzapp API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Tessera
 */
export interface Tessera {
    /**
     * 
     * @type {string}
     * @memberof Tessera
     */
    carburante: TesseraCarburanteEnum;
    /**
     * 
     * @type {Cittadino}
     * @memberof Tessera
     */
    cittadino?: any;
    /**
     * 
     * @type {string}
     * @memberof Tessera
     */
    codice: any;
    /**
     * 
     * @type {Date}
     * @memberof Tessera
     */
    dataEmissione: any;
    /**
     * 
     * @type {Array&lt;Delega&gt;}
     * @memberof Tessera
     */
    delegas?: any;
    /**
     * 
     * @type {number}
     * @memberof Tessera
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Tessera
     */
    immagine?: any;
    /**
     * 
     * @type {string}
     * @memberof Tessera
     */
    immagineContentType?: any;
    /**
     * 
     * @type {Array&lt;Rifornimento&gt;}
     * @memberof Tessera
     */
    rifornimentos?: any;
    /**
     * 
     * @type {string}
     * @memberof Tessera
     */
    targa: any;
    /**
     * 
     * @type {string}
     * @memberof Tessera
     */
    veicolo: TesseraVeicoloEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum TesseraCarburanteEnum {
    BENZINA = 'BENZINA',
    DIESEL = 'DIESEL'
}
/**
    * @export
    * @enum {string}
    */
export enum TesseraVeicoloEnum {
    AUTOVEICOLO = 'AUTOVEICOLO',
    CICLOMOTORE = 'CICLOMOTORE',
    MOTOVEICOLO = 'MOTOVEICOLO'
}

