/* tslint:disable */
/* eslint-disable */
/**
 * benzapp API
 * benzapp API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    activated: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    firstName?: any;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    imageUrl?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    langKey?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    lastName?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    login: any;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    resetDate?: any;
}
