/**
 * benzapp API
 * benzapp API documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, {AxiosPromise, AxiosInstance} from 'axios';
import {Configuration} from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import {BASE_PATH, RequestArgs, BaseAPI} from '../base';
import {Device} from '../models';

/**
 * DeviceResourceApi - axios parameter creator
 * @export
 */
export const DeviceResourceApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary createDevice
     * @param {Device} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createDeviceUsingPOST: async (body?: Device, options: any = {}): Promise<RequestArgs> => {
      const localVarPath = `/api/devices`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, 'https://example.com');
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions = {method: 'POST', ...baseOptions, ...options};
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication benzappAuth required
      const authHeader = {'Authorization': `Bearer ${configuration!.accessToken}`};

      localVarHeaderParameter['Content-Type'] = 'application/json';

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.query) {
        query.set(key, options.query[key]);
      }
      localVarUrlObj.search = (new URLSearchParams(query)).toString();
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers, ...authHeader};
      const needsSerialization = true;
      localVarRequestOptions.data = needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || '');

      return {
        url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
  }
};

/**
 * DeviceResourceApi - functional programming interface
 * @export
 */
export const DeviceResourceApiFp = function (configuration?: Configuration) {
  return {

    /**
     *
     * @summary createDevice
     * @param {Device} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createDeviceUsingPOST(body?: Device, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Device>> {
      const localVarAxiosArgs = await DeviceResourceApiAxiosParamCreator(configuration).createDeviceUsingPOST(body, options);
      return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
        const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
        return axios.request(axiosRequestArgs);
      };
    },
  }
};

/**
 * DeviceResourceApi - object-oriented interface
 * @export
 * @class DeviceResourceApi
 * @extends {BaseAPI}
 */
export class DeviceResourceApi extends BaseAPI {


  /**
   *
   * @summary createDevice
   * @param {Device} [body]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DeviceResourceApi
   */
  public createDeviceUsingPOST(body?: Device, options?: any) {
    return DeviceResourceApiFp(this.configuration).createDeviceUsingPOST(body, options).then((request) => request(this.axios, this.basePath));
  }
}
