/* tslint:disable */
/* eslint-disable */
/**
 * benzapp API
 * benzapp API documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Fascia } from '../models';
/**
 * FasciaResourceApi - axios parameter creator
 * @export
 */
export const FasciaResourceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *
         * @summary createFascia
         * @param {Fascia} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createFasciaUsingPOST: async (body?: Fascia, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/fascias`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication benzappAuth required
          const authHeader = {'Authorization':  `Bearer ${configuration!.accessToken}`};

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary deleteFascia
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteFasciaUsingDELETE: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling deleteFasciaUsingDELETE.');
            }
            const localVarPath = `/api/fascias/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication benzappAuth required
          const authHeader = {'Authorization':  `Bearer ${configuration!.accessToken}`};

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary getAllFascias
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllFasciasUsingGET: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/fascias`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication benzappAuth required
          const authHeader = {'Authorization':  `Bearer ${configuration!.accessToken}`};

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary getFascia
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFasciaUsingGET: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getFasciaUsingGET.');
            }
            const localVarPath = `/api/fascias/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication benzappAuth required
          const authHeader = {'Authorization':  `Bearer ${configuration!.accessToken}`};

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary partialUpdateFascia
         * @param {Fascia} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        partialUpdateFasciaUsingPATCH: async (body?: Fascia, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/fascias`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication benzappAuth required
          const authHeader = {'Authorization':  `Bearer ${configuration!.accessToken}`};

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary updateFascia
         * @param {Fascia} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateFasciaUsingPUT: async (body?: Fascia, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/fascias`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication benzappAuth required
          const authHeader = {'Authorization':  `Bearer ${configuration!.accessToken}`};

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FasciaResourceApi - functional programming interface
 * @export
 */
export const FasciaResourceApiFp = function(configuration?: Configuration) {
    return {
        /**
         *
         * @summary createFascia
         * @param {Fascia} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createFasciaUsingPOST(body?: Fascia, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Fascia>> {
            const localVarAxiosArgs = await FasciaResourceApiAxiosParamCreator(configuration).createFasciaUsingPOST(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @summary deleteFascia
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteFasciaUsingDELETE(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await FasciaResourceApiAxiosParamCreator(configuration).deleteFasciaUsingDELETE(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @summary getAllFascias
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllFasciasUsingGET(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Fascia>>> {
            const localVarAxiosArgs = await FasciaResourceApiAxiosParamCreator(configuration).getAllFasciasUsingGET(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @summary getFascia
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFasciaUsingGET(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Fascia>> {
            const localVarAxiosArgs = await FasciaResourceApiAxiosParamCreator(configuration).getFasciaUsingGET(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @summary partialUpdateFascia
         * @param {Fascia} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async partialUpdateFasciaUsingPATCH(body?: Fascia, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Fascia>> {
            const localVarAxiosArgs = await FasciaResourceApiAxiosParamCreator(configuration).partialUpdateFasciaUsingPATCH(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         *
         * @summary updateFascia
         * @param {Fascia} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateFasciaUsingPUT(body?: Fascia, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Fascia>> {
            const localVarAxiosArgs = await FasciaResourceApiAxiosParamCreator(configuration).updateFasciaUsingPUT(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * FasciaResourceApi - factory interface
 * @export
 */
export const FasciaResourceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         *
         * @summary createFascia
         * @param {Fascia} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createFasciaUsingPOST(body?: Fascia, options?: any): AxiosPromise<Fascia> {
            return FasciaResourceApiFp(configuration).createFasciaUsingPOST(body, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary deleteFascia
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteFasciaUsingDELETE(id: number, options?: any): AxiosPromise<void> {
            return FasciaResourceApiFp(configuration).deleteFasciaUsingDELETE(id, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary getAllFascias
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllFasciasUsingGET(options?: any): AxiosPromise<Array<Fascia>> {
            return FasciaResourceApiFp(configuration).getAllFasciasUsingGET(options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary getFascia
         * @param {number} id id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFasciaUsingGET(id: number, options?: any): AxiosPromise<Fascia> {
            return FasciaResourceApiFp(configuration).getFasciaUsingGET(id, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary partialUpdateFascia
         * @param {Fascia} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        partialUpdateFasciaUsingPATCH(body?: Fascia, options?: any): AxiosPromise<Fascia> {
            return FasciaResourceApiFp(configuration).partialUpdateFasciaUsingPATCH(body, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary updateFascia
         * @param {Fascia} [body]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateFasciaUsingPUT(body?: Fascia, options?: any): AxiosPromise<Fascia> {
            return FasciaResourceApiFp(configuration).updateFasciaUsingPUT(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FasciaResourceApi - object-oriented interface
 * @export
 * @class FasciaResourceApi
 * @extends {BaseAPI}
 */
export class FasciaResourceApi extends BaseAPI {
    /**
     *
     * @summary createFascia
     * @param {Fascia} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FasciaResourceApi
     */
    public createFasciaUsingPOST(body?: Fascia, options?: any) {
        return FasciaResourceApiFp(this.configuration).createFasciaUsingPOST(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary deleteFascia
     * @param {number} id id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FasciaResourceApi
     */
    public deleteFasciaUsingDELETE(id: number, options?: any) {
        return FasciaResourceApiFp(this.configuration).deleteFasciaUsingDELETE(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary getAllFascias
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FasciaResourceApi
     */
    public getAllFasciasUsingGET(options?: any) {
        return FasciaResourceApiFp(this.configuration).getAllFasciasUsingGET(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary getFascia
     * @param {number} id id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FasciaResourceApi
     */
    public getFasciaUsingGET(id: number, options?: any) {
        return FasciaResourceApiFp(this.configuration).getFasciaUsingGET(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary partialUpdateFascia
     * @param {Fascia} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FasciaResourceApi
     */
    public partialUpdateFasciaUsingPATCH(body?: Fascia, options?: any) {
        return FasciaResourceApiFp(this.configuration).partialUpdateFasciaUsingPATCH(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary updateFascia
     * @param {Fascia} [body]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FasciaResourceApi
     */
    public updateFasciaUsingPUT(body?: Fascia, options?: any) {
        return FasciaResourceApiFp(this.configuration).updateFasciaUsingPUT(body, options).then((request) => request(this.axios, this.basePath));
    }
}
