/* tslint:disable */
/* eslint-disable */
/**
 * benzapp API
 * benzapp API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */export * from './apis/account-resource-api';
export * from './apis/cittadino-resource-api';
export * from './apis/delega-resource-api';
export * from './apis/device-resource-api';
export * from './apis/fascia-resource-api';
export * from './apis/gestore-resource-api';
export * from './apis/marchio-resource-api';
export * from './apis/notifica-resource-api';
export * from './apis/public-user-resource-api';
export * from './apis/rifornimento-resource-api';
export * from './apis/tessera-resource-api';
export * from './apis/user-jwt-controller-api';
export * from './apis/user-resource-api';

